//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VISA_SYSTEM_ONLINE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISA_User_Login
    {
        public int RecNo { get; set; }
        public string Opno { get; set; }
        public string Password { get; set; }
        public string OP_Name { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string Authority { get; set; }
    }
}
